# Generated by Django 5.1.1 on 2024-10-25 09:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clients_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Mail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('topic', models.CharField(max_length=35, verbose_name='тема письма')),
                ('content', models.TextField(verbose_name='тело письма')),
            ],
        ),
        migrations.CreateModel(
            name='MailingTrying',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_mailing', models.DateTimeField(verbose_name='последняя рассылка')),
                ('status_trying', models.BooleanField()),
                ('server_response', models.CharField(max_length=35)),
            ],
        ),
        migrations.CreateModel(
            name='Mailing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_mailing', models.DateTimeField(blank=True, null=True, verbose_name='первая рассылка')),
                ('periodicity', models.PositiveBigIntegerField(default=60, verbose_name='переодичность')),
                ('status', models.CharField(max_length=35, verbose_name='статус')),
                ('clients', models.ManyToManyField(to='clients_app.client')),
                ('mail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mailing_app.mail')),
            ],
        ),
    ]
