# Generated by Django 5.1.3 on 2024-12-23 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mailing_app", "0003_alter_mailing_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="mailing",
            name="is_active",
            field=models.BooleanField(default=True, verbose_name="статус рассылки"),
        ),
    ]
