# Generated by Django 5.1.3 on 2024-12-23 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mailing_app", "0004_mailing_is_active"),
    ]

    operations = [
        migrations.AddField(
            model_name="mailing",
            name="time_next_mailing",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="время следующей рассылки"
            ),
        ),
    ]
