# Generated by Django 5.1.3 on 2024-12-23 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mailing_app", "0006_alter_mailing_periodicity"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mailingtrying",
            name="status_trying",
            field=models.CharField(
                choices=[("SC", "Успешно"), ("FL", "Неуспешно")],
                max_length=2,
                verbose_name="статус попытки",
            ),
        ),
    ]
