# Generated by Django 5.1.3 on 2024-12-26 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mailing_app", "0008_alter_mailingtrying_server_response"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="mailing",
            name="is_active",
        ),
        migrations.RemoveField(
            model_name="mailing",
            name="periodicity",
        ),
        migrations.RemoveField(
            model_name="mailing",
            name="time_next_mailing",
        ),
        migrations.AddField(
            model_name="mailing",
            name="frequency",
            field=models.CharField(
                choices=[
                    ("DY", "Раз в день"),
                    ("WE", "Раз в неделю"),
                    ("MN", "Раз в месяц"),
                ],
                default="DY",
                max_length=2,
                verbose_name="Периодичность",
            ),
        ),
        migrations.AddField(
            model_name="mailing",
            name="next_mailing",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Следующая рассылка"
            ),
        ),
    ]
