# Generated by Django 5.1.3 on 2025-01-08 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mailing_app', '0009_remove_mailing_is_active_remove_mailing_periodicity_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mailing',
            name='next_mailing',
            field=models.DateTimeField(blank=True, verbose_name='Следующая рассылка'),
        ),
    ]
