# Generated by Django 5.1.3 on 2025-01-04 13:40

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "mailing_app",
            "0009_remove_mailing_is_active_remove_mailing_periodicity_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="mailing",
            name="next_mailing",
            field=models.DateTimeField(
                blank=True,
                default=django.utils.timezone.now,
                verbose_name="Следующая рассылка",
            ),
        ),
    ]
