# Generated by Django 5.1.3 on 2025-05-17 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mailing_app", "0010_alter_mailing_next_mailing"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mailingtrying",
            name="status_trying",
            field=models.CharField(
                choices=[("SC", "Успешно"), ("FL", "Неуспешно")],
                max_length=30,
                verbose_name="статус попытки",
            ),
        ),
    ]
