# Generated by Django 5.1.3 on 2025-05-23 09:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mailing_app", "0011_alter_mailingtrying_status_trying"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mailing",
            name="status",
            field=models.CharField(
                choices=[("CR", "Создана"), ("RN", "Запущена"), ("FS", "Завершена")],
                default="CR",
                max_length=2,
                verbose_name="статус",
            ),
        ),
    ]
