# Generated by Django 5.1.3 on 2025-06-15 11:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mailing_app", "0013_alter_mailing_mail"),
    ]

    operations = [
        migrations.AddField(
            model_name="mailing",
            name="is_immediate",
            field=models.BooleanField(
                default=False, verbose_name="Немедленная отправка"
            ),
        ),
        migrations.AddField(
            model_name="mailing",
            name="last_try",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Последняя попытка"
            ),
        ),
        migrations.AlterField(
            model_name="mailing",
            name="frequency",
            field=models.CharField(
                choices=[
                    ("ON", "Один раз"),
                    ("DY", "Раз в день"),
                    ("WE", "Раз в неделю"),
                    ("MN", "Раз в месяц"),
                ],
                default="DY",
                max_length=2,
            ),
        ),
        migrations.AlterField(
            model_name="mailing",
            name="next_mailing",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Следующая рассылка"
            ),
        ),
        migrations.AlterField(
            model_name="mailing",
            name="status",
            field=models.CharField(
                choices=[
                    ("CR", "Создана"),
                    ("RN", "Запущена"),
                    ("FS", "Завершена"),
                    ("FL", "Ошибка"),
                ],
                default="CR",
                max_length=2,
            ),
        ),
        migrations.AlterField(
            model_name="mailingtrying",
            name="mailing",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="mailing_app.mailing"
            ),
        ),
    ]
