# Generated by Django 5.1.3 on 2025-06-16 09:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("clients_app", "0002_alter_client_options"),
        ("mailing_app", "0014_mailing_is_immediate_mailing_last_try_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="mail",
            options={
                "permissions": [
                    ("can_view_mailing", "Просмотр рассылок"),
                    ("can_delete_mailing", "Отключение рассылок"),
                ],
                "verbose_name": "письмо",
                "verbose_name_plural": "письма",
            },
        ),
        migrations.AlterModelOptions(
            name="mailing",
            options={
                "permissions": [
                    ("can_view_mailing", "Просмотр рассылок"),
                    ("can_delete_mailing", "Отключение рассылок"),
                ],
                "verbose_name": "рассылка",
                "verbose_name_plural": "рассылки",
            },
        ),
        migrations.AlterModelOptions(
            name="mailingtrying",
            options={
                "verbose_name": "попытка рассылки",
                "verbose_name_plural": "попытки рассылок",
            },
        ),
        migrations.AlterField(
            model_name="mailing",
            name="clients",
            field=models.ManyToManyField(
                to="clients_app.client", verbose_name="Клиенты"
            ),
        ),
        migrations.AlterField(
            model_name="mailing",
            name="frequency",
            field=models.CharField(
                choices=[
                    ("ON", "Один раз"),
                    ("DY", "Раз в день"),
                    ("WE", "Раз в неделю"),
                    ("MN", "Раз в месяц"),
                ],
                default="DY",
                max_length=2,
                verbose_name="Периодичность",
            ),
        ),
        migrations.AlterField(
            model_name="mailing",
            name="mail",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="mails",
                to="mailing_app.mail",
                verbose_name="Письмо",
            ),
        ),
        migrations.AlterField(
            model_name="mailing",
            name="status",
            field=models.CharField(
                choices=[
                    ("CR", "Создана"),
                    ("RN", "Запущена"),
                    ("FS", "Завершена"),
                    ("FL", "Ошибка"),
                ],
                default="CR",
                max_length=2,
                verbose_name="Статус",
            ),
        ),
    ]
